### ISSUE TITLE
code range of Cache client

### ISSUE THREAD

**Issue by skyao** [naver/pinpoint-plugin-sample#21]
In the document of "Pinpoint Profiler Plugin Sample" (https://github.com/naver/pinpoint-plugin-sample), chapter "ServiceType codes for private use", I found this:

> Cache client: 8999 ~ 8999

This code range is not reasonable so I think perhaps there is a small mistaken ? 

Please help to check it, thank you !

PS: thank you so much for this great product ! I like it!

**Comment by lioolli** [comment]
I have fixed the typo. Thanks for your infromation.
